spring.application.name=Terra Bucovina Backend
spring.security.user.password=1234
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
server.port=${PORT:8080}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


#spring.datasource.hikari.pool-name=HikariPool-1
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2

app.jwt.secret=XOyUXC8cQx0d+5Q2D0GGtTGAoAVNqyx7AFZsuQjLQr+6SUl1kBO4PpInsa6Jlqb9caDxAn8OBH8F1HlebKuemQ==
app.jwt.expiration-ms=9600000   


gmail.username=tamasagiuliana@gmail.com
gmail.password=${EMAIL_PASS}


#app.jwt.refresh-expiration-ms=1209600000 # 14 days (if using refresh tokens)

app.images.dir=/app/uploads/images

logging.level.org.springframework.web=DEBUG
