spring.application.name=Terra Bucovina Backend

spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:49945?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
server.port=${MYSQLPORT}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#debug=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG


#spring.datasource.hikari.pool-name=HikariPool-1
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2

app.jwt.secret=XOyUXC8cQx0d+5Q2D0GGtTGAoAVNqyx7AFZsuQjLQr+6SUl1kBO4PpInsa6Jlqb9caDxAn8OBH8F1HlebKuemQ==
app.jwt.expiration-ms=9600000   


gmail.username=tamasagiuliana@gmail.com
gmail.password=${EMAIL_PASS}


#app.jwt.refresh-expiration-ms=1209600000 # 14 days (if using refresh tokens)

app.images.dir=/app/uploads/images

logging.level.org.springframework.web=DEBUG
